package com.egzaminator.components;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

@Component
@Scope("prototype")
public class AppView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,16","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private StartView content;
	@AutoGenerated
	private NavigationView nav;
	@AutoGenerated
	private FooterView footer;
	@AutoGenerated
	private LeftPanelView left;
	@AutoGenerated
	private HeaderView header;
	
	@Autowired
	AuthenticationManager auth;
	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AppView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		addComponents();
	}

	
	public void addComponents() {
		
		//header
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1243px");
		mainLayout.setHeight("822px");
		
		// top-level component properties
		setWidth("1243px");
		setHeight("822px");
		
		// header
		header = new HeaderView();
		header.setImmediate(false);
		header.setWidth("1054px");
		header.setHeight("60px");
		mainLayout.addComponent(header, "top:20.0px;left:0.0px;");
		
		// left
		left = new LeftPanelView();
		left.setImmediate(false);
		left.setWidth("110px");
		left.setHeight("600px");
		mainLayout.addComponent(left, "top:78.0px;left:0.0px;");
		
		// footer
		footer = new FooterView();
		footer.setImmediate(false);
		footer.setWidth("1054px");
		footer.setHeight("60px");
		mainLayout.addComponent(footer, "top:678.0px;left:0.0px;");
		
		// nav
		nav = new NavigationView();
		nav.setImmediate(false);
		nav.setWidth("944px");
		nav.setHeight("40px");
		mainLayout.addComponent(nav, "top:78.0px;left:110.0px;");
		
		// content
		content = new StartView();
		content.setImmediate(false);
		content.setWidth("944px");
		content.setHeight("562px");
		mainLayout.addComponent(content, "top:116.0px;left:110.0px;");
		
		return mainLayout;
	}

}
