package com.egzaminator.components;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.egzaminator.dao.UserDAOImpl;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

@Component
@Scope("session")
public class HeadComp extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,11","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":9} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private NavigationView navComp_2;

	@AutoGenerated
	private LeftPanelView leftPanelComp_1;

	@Autowired
	private UserDAOImpl userDao;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HeadComp() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	
	// GETTERS / SETTERS
	
	public void setUserDao(UserDAOImpl userDao) {
		this.userDao = userDao;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// leftPanelComp_1
		leftPanelComp_1 = new LeftPanelView();
		leftPanelComp_1.setImmediate(false);
		leftPanelComp_1.setWidth("105px");
		leftPanelComp_1.setHeight("261px");
		mainLayout.addComponent(leftPanelComp_1, "top:40.0px;left:5.0px;");
		
		// navComp_2
		navComp_2 = new NavigationView();
		navComp_2.setImmediate(false);
		navComp_2.setWidth("1000px");
		navComp_2.setHeight("92px");
		mainLayout.addComponent(navComp_2, "top:40.0px;left:110.0px;");
		
		return mainLayout;
	}
	

}
