package com.egzaminator.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.TextField;

public class NavComp extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private MenuBar menuBar_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public NavComp() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2, "top:20.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("780px");
		horizontalLayout_2.setHeight("60px");
		horizontalLayout_2.setMargin(false);
		
		// menuBar_1
		menuBar_1 = new MenuBar();
		menuBar_1.setImmediate(false);
		//menuBar_1.setWidth("100%");
		menuBar_1.setHeight("-1px");
		menuBar_1.addItem("ADMINISTRACJA", null);
		menuBar_1.addItem("KANDYDACI", null);
		menuBar_1.addItem("TESTY", null);
		horizontalLayout_2.addComponent(menuBar_1);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		//textField_2.setWidth("100%");
		textField_2.setHeight("-1px");
		horizontalLayout_2.addComponent(textField_2);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(false);
		//button_1.setWidth("100%");
		button_1.setHeight("-1px");
		horizontalLayout_2.addComponent(button_1);
		
		horizontalLayout_2.setExpandRatio(menuBar_1, 4.0f);
		horizontalLayout_2.setExpandRatio(textField_2, 1.7f);
		return horizontalLayout_2;
	}

}
