package com.egzaminator.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;

public class NavigationView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,17","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private MenuBar navBar;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public NavigationView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		buildMenuBar();
	}
	
	private void buildMenuBar() {
		
		navBar.addItem("ADMINISTRACJA", null);
		navBar.addItem("KANDYDACI", null);
		navBar.addItem("TESTY", null);
	}

	

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// navBar
		navBar = new MenuBar();
		navBar.setImmediate(false);
		navBar.setWidth("-1px");
		navBar.setHeight("-1px");
		mainLayout.addComponent(navBar);
		mainLayout.setExpandRatio(navBar, 2.0f);
		mainLayout.setComponentAlignment(navBar, new Alignment(33));
		
		return mainLayout;
	}

}
