package com.egzaminator.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;

public class MainUI extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Accordion accordion_1;
	@AutoGenerated
	private CheckBox checkBox_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// accordion_1
		accordion_1 = buildAccordion_1();
		mainLayout.addComponent(accordion_1,
				"top:40.0px;bottom:63.0px;left:80.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Accordion buildAccordion_1() {
		// common part: create layout
		accordion_1 = new Accordion();
		accordion_1.setImmediate(true);
		accordion_1.setWidth("240px");
		accordion_1.setHeight("100.0%");
		
		// checkBox_1
		checkBox_1 = new CheckBox();
		checkBox_1.setCaption("Zgadzam sie");
		checkBox_1.setImmediate(false);
		checkBox_1.setWidth("-1px");
		checkBox_1.setHeight("-1px");
		checkBox_1.setInvalidAllowed(false);
		accordion_1.addTab(checkBox_1, "Test1", null);
		
		return accordion_1;
	}

}
